<?php

namespace Rhino\Blueprint\Generators;

use Illuminate\Support\Str;

class SeederGenerator
{
    /**
     * Generate a RoleSeeder file content from parsed roles.
     *
     * Only applicable for multi-tenant apps (where Role model exists).
     *
     * @param array $roles Parsed roles from BlueprintParser::parseRoles()
     * @return string Generated PHP seeder file content
     */
    public function generateRoleSeeder(array $roles): string
    {
        $roleCreations = '';

        foreach ($roles as $slug => $definition) {
            $name = addslashes($definition['name']);
            $description = addslashes($definition['description']);

            $roleCreations .= <<<PHP
        Role::firstOrCreate(
            ['slug' => '{$slug}'],
            [
                'name' => '{$name}',
                'description' => '{$description}',
            ]
        );

PHP;
        }

        return <<<PHP
<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

/**
 * Seeds roles from Rhino Blueprint definitions.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify _roles.yaml and run: php artisan rhino:blueprint
 */
class RoleSeeder extends Seeder
{
    public function run(): void
    {
{$roleCreations}    }
}

PHP;
    }

    /**
     * Generate a UserRoleSeeder file content from aggregated permissions (multi-tenant).
     *
     * Creates users with roles and permissions via the UserRole pivot table.
     * Requires Organization, Role, and UserRole models.
     *
     * @param array $roles Parsed roles
     * @param array $aggregatedPermissions Role => permission strings, aggregated from all blueprints
     * @return string Generated PHP seeder file content
     */
    public function generateUserRoleSeeder(array $roles, array $aggregatedPermissions): string
    {
        $assignments = '';

        foreach ($roles as $slug => $definition) {
            $name = $definition['name'];
            $varName = Str::camel($slug);
            $permissions = $aggregatedPermissions[$slug] ?? [];
            $permPhp = $this->permissionsToPhpArray($permissions);

            $assignments .= <<<PHP
        // {$name}
        \${$varName}User = User::factory()->create([
            'name' => '{$name} User',
            'email' => '{$slug}@example.com',
        ]);
        \${$varName}Role = Role::where('slug', '{$slug}')->firstOrFail();
        UserRole::firstOrCreate(
            ['user_id' => \${$varName}User->id, 'role_id' => \${$varName}Role->id, 'organization_id' => \$org->id],
            ['permissions' => {$permPhp}]
        );

PHP;
        }

        return <<<PHP
<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\Role;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Database\Seeder;

/**
 * Seeds sample users with role-based permissions from Rhino Blueprint definitions.
 *
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify blueprint files and run: php artisan rhino:blueprint
 */
class UserRoleSeeder extends Seeder
{
    public function run(): void
    {
        \$org = Organization::firstOrCreate(
            ['slug' => 'demo-org'],
            [
                'name' => 'Demo Organization',
                'description' => 'Default organization for development',
                'is_active' => true,
            ]
        );

{$assignments}    }
}

PHP;
    }

    /**
     * Generate a UserPermissionSeeder for non-tenant apps.
     *
     * Creates users with permissions stored directly on the User model's
     * `permissions` JSON column. No Role, Organization, or UserRole models needed.
     *
     * @param array $roles Parsed roles (used for naming/describing users)
     * @param array $aggregatedPermissions Role => permission strings, aggregated from all blueprints
     * @return string Generated PHP seeder file content
     */
    public function generateUserPermissionSeeder(array $roles, array $aggregatedPermissions): string
    {
        $assignments = '';

        foreach ($roles as $slug => $definition) {
            $name = $definition['name'];
            $varName = Str::camel($slug);
            $permissions = $aggregatedPermissions[$slug] ?? [];
            $permPhp = $this->permissionsToPhpArray($permissions);

            $assignments .= <<<PHP
        // {$name}
        User::factory()->create([
            'name' => '{$name} User',
            'email' => '{$slug}@example.com',
            'permissions' => {$permPhp},
        ]);

PHP;
        }

        return <<<PHP
<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * Seeds sample users with permissions from Rhino Blueprint definitions.
 *
 * Permissions are stored directly on the User model's `permissions` column.
 * Generated by Rhino Blueprint — zero-token deterministic generation.
 * To regenerate, modify blueprint files and run: php artisan rhino:blueprint
 */
class UserPermissionSeeder extends Seeder
{
    public function run(): void
    {
{$assignments}    }
}

PHP;
    }

    /**
     * Aggregate permissions from all parsed blueprints into per-role arrays.
     *
     * @param array $blueprints Array of parsed blueprints
     * @return array<string, string[]> Role slug => array of permission strings
     */
    public function aggregatePermissions(array $blueprints): array
    {
        $aggregated = [];

        foreach ($blueprints as $blueprint) {
            $slug = $blueprint['slug'];
            $permissions = $blueprint['permissions'] ?? [];

            foreach ($permissions as $role => $definition) {
                if (!isset($aggregated[$role])) {
                    $aggregated[$role] = [];
                }

                $actions = $definition['actions'] ?? [];

                // Check if all actions = wildcard
                $allActions = ['index', 'show', 'store', 'update', 'destroy', 'trashed', 'restore', 'forceDelete'];
                if (count(array_diff($allActions, $actions)) === 0) {
                    $aggregated[$role][] = "{$slug}.*";
                } else {
                    foreach ($actions as $action) {
                        $aggregated[$role][] = "{$slug}.{$action}";
                    }
                }
            }
        }

        // Sort permissions for readability
        foreach ($aggregated as $role => &$perms) {
            sort($perms);
            $perms = array_unique($perms);
        }

        // Check if any role has wildcard for ALL models — simplify to ['*']
        foreach ($aggregated as $role => &$perms) {
            $allWildcard = true;
            foreach ($blueprints as $blueprint) {
                $slug = $blueprint['slug'];
                if (!in_array("{$slug}.*", $perms)) {
                    $allWildcard = false;
                    break;
                }
            }

            if ($allWildcard && count($blueprints) > 0) {
                $perms = ['*'];
            }
        }

        return $aggregated;
    }

    /**
     * Convert a permissions array to a PHP array string.
     */
    protected function permissionsToPhpArray(array $permissions): string
    {
        if (empty($permissions)) {
            return '[]';
        }

        if ($permissions === ['*']) {
            return "['*']";
        }

        $items = array_map(fn($p) => "'{$p}'", $permissions);

        // Single line if short enough
        $inline = '[' . implode(', ', $items) . ']';
        if (strlen($inline) <= 80) {
            return $inline;
        }

        // Multi-line for long permission arrays
        $lines = implode(",\n                ", $items);
        return "[\n                {$lines},\n            ]";
    }
}
